run:
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - errcheck
    - gosec
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - noctx
  presets:
    - bugs

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
