name: Lint and test
description: Lint and test go code

runs:
  using: composite
  steps:
    - name: Run linting
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
    - name: Run tests
      shell: bash
      run: go test -v -coverprofile=coverage.out ./...
