name: Setup Go
description: Setup Go

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Install dependencies
      shell: bash
      run: go mod download
