name: Setup Go
description: Setup Go

inputs:
  working-directory:
    description: 'Directory containing the Go module to set up'
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download

    - uses: brokeyourbike/go-mockery-action@v0
      with:
        mockery-version: 2.52.4
