name: CI checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  find-modules:
    name: Find Go modules
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.find-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get install -y jq
      - id: find-modules
        uses: ./.github/actions/find-modules

  check-modules:
    name: Check Go modules
    needs: find-modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.find-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
        with:
          working-directory: ${{ matrix.module }}
      - uses: ./.github/actions/go-checks
        with:
          working-directory: ${{ matrix.module }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.module != './examples' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SvenvDam/linea
          flags: ${{ matrix.module }}
          files: ${{ matrix.module }}/coverage.out
