name: CI checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run CI checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/lint-test
