name: CI checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run CI checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/lint-test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SvenvDam/linea
          files: coverage.out
