name: On PR

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install dependencies
        run: go mod download
      - name: Run linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run tests
        run: go test -v ./...
